# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/chy/Digital design/project_1/project_1.cache/wt} [current_project]
set_property parent.project_path {D:/chy/Digital design/project_1/project_1.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {D:/chy/Digital design/project_1/sign_extension.v}
  {D:/chy/Digital design/project_1/regfile.v}
  {D:/chy/Digital design/project_1/progcounter.v}
  {D:/chy/Digital design/project_1/mux_2to1.v}
  {D:/chy/Digital design/project_1/datamem.v}
  {D:/chy/Digital design/project_1/ctrlunit.v}
  {D:/chy/Digital design/project_1/alu.v}
  {D:/chy/Digital design/project_1/instmem.v}
  {D:/chy/Digital design/project_1/cpu.v}
  {D:/chy/Digital design/project_1/project_1.srcs/sources_1/new/pc.v}
}
synth_design -top pc -part xc7a100tcsg324-1
write_checkpoint -noxdef pc.dcp
catch { report_utilization -file pc_utilization_synth.rpt -pb pc_utilization_synth.pb }
